---
title: "SENTINEL Sensor Report "
header-includes: \usepackage{float}
output: 
  html_document: 
    fig_crop: no
params:
  plotBC:
  plotWD:
  plotCT:
  plotRH:
  plotT:
  plotCAL:
  WR:
  SDI:
  SN:
  OutputDate:
always_allow_html: true
---

```{r setup, include=FALSE}

```

```{r echo=FALSE, message=FALSE, warning=FALSE, results= "asis"}
# create leading lines of document
a <- paste0("Sensor Unit: ", params$SN)
e <- paste0("Output Date: ", params$OutputDate)
i <- paste0("  ")
cat(paste0(
           a, '\n','\n',
           e, '\n','\n',
           i, '\n','\n'
  ))

```

Wind Rose and Source Direction Indicator Plots

```{r, fig.height=4, fig.width=9, out.height="100%", out.width="100%", echo=FALSE, error=FALSE, warning=FALSE, message = FALSE, fig.pos='H'}
WR <- params$WR 
SDI <- params$SDI

WR
SDI

```

Time Series Plots

##### Baseline Corrected Signal 

```{r, fig.height=4, fig.width=9, out.height="100%", out.width="100%", echo=FALSE, error=FALSE, warning=FALSE, message = FALSE, fig.pos='H'}
# Baseline Correction and Signal 
fig <- params$plotBC %>%  
  layout(autosize = F, width = 1000, height = 500)
tmpFile <- tempfile(fileext = ".png")
export(fig, file = tmpFile)
```

##### Wind Direction & Signal 

```{r, fig.height=4, fig.width=9, out.height="100%", out.width="100%", echo=FALSE, error=FALSE, warning=FALSE, message = FALSE,fig.pos='H'}
fig2 <- params$plotWD %>%  
  layout(autosize = F,width = 1000, height = 500)
tmpFile2 <- tempfile(fileext = ".png")
export(fig2, file = tmpFile2)
```

##### Canister Triggers & Signal 

```{r, fig.height=4, fig.width=9, out.height="100%", out.width="100%", echo=FALSE, error=FALSE, warning=FALSE, message = FALSE, fig.pos='H'}
fig3 <- params$plotCT %>%  
  layout(autosize = F, width = 1000, height = 500)
tmpFile3 <- tempfile(fileext = ".png")
export(fig3, file = tmpFile3)

```

##### Relative Humidity & Signal 

```{r, fig.height=4, fig.width=9, out.height="100%", out.width="100%", echo=FALSE, error=FALSE, warning=FALSE, message = FALSE, fig.pos='H'}
fig3 <- params$plotRH %>%  
  layout(autosize = F, width = 1000, height = 500)
tmpFile3 <- tempfile(fileext = ".png")
export(fig3, file = tmpFile3)

```

##### Temperature & Signal 

```{r, fig.height=4, fig.width=9, out.height="100%", out.width="100%", echo=FALSE, error=FALSE, warning=FALSE, message = FALSE, fig.pos='H'}
fig3 <- params$plotT %>%  
  layout(autosize = F, width = 1000, height = 500)
tmpFile3 <- tempfile(fileext = ".png")
export(fig3, file = tmpFile3)

```

##### Calibrations & Signal 

```{r, fig.height=4, fig.width=9, out.height="100%", out.width="100%", echo=FALSE, error=FALSE, warning=FALSE, message = FALSE, fig.pos='H'}
fig3 <- params$plotCAL %>%  
  layout(autosize = F, width = 1000, height = 500)
tmpFile3 <- tempfile(fileext = ".png")
export(fig3, file = tmpFile3)

```
